version: "3.7"

services:
  server:
    image: linuxserver/plex:1.40.0@sha256:3bc1444e7e8a91dfa0735b1878b4f0eb39c680e97ed419149f74ef24cd1c9222
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    ports:
      - 32400:32400
      # Plex Companion
      - 3005:3005/tcp
      # Roku via Plex Companion
      - 8324:8324/tcp
      # Plex DLNA Server
      - 32469:32469/tcp 
      - 1900:1900/udp
      # Network discovery
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
